Traceback (most recent call last):
  File "/home/pi/shp/Raspberry/socketserver.py", line 332, in <module>
    main()
  File "/home/pi/shp/Raspberry/socketserver.py", line 326, in main
    start(listIPAdressClient, localDataContent)
  File "/home/pi/shp/Raspberry/socketserver.py", line 288, in start
    if(sys.argv[1] != "-without" and sys.argv[2] !="mariaDB"):
IndexError: list index out of range

Ce problème a été résolu en modifiant l'exécution de Start_CleverTreeServer.py a Start_CleverTreeServer.py -with maria

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/shp/Raspberry/socketserver.py", line 247, in handle_client
    DataContent[4] = MsgInArray[2]
IndexError: list index out of range

Ce problème a été résolu en modifiant le fichier socketclient.py pour séparer les données par des points au lieu des virgules

Traceback (most recent call last):
  File "/home/pi/shp/Raspberry/socketserver.py", line 34, in <module>
    server.bind(ADDR)
OSError: [Errno 98] Address already in use

Ce problème a été résolu en changeant la valeur de la variable SERVER

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/shp/Raspberry/socketserver.py", line 268, in handle_client
    StartMariaDBServer()[0].execute(sql, val)
  File "/home/pi/shp/Raspberry/socketserver.py", line 47, in StartMariaDBServer
    mycursor
UnboundLocalError: local variable 'mycursor' referenced before assignment

Ce problème a été résolu en retirant la prédéclaration de la variable mycursor
